name: ViperBows
version: '${version}'
main: dev.pixl.plugins.viperbows.ViperBowsPlugin
api-version: '1.20'
commands:
  vbcreate:
    permission: viperbows.command.vbcreate
    permission-message: No.
    description: Create a sample bow with the explosive ability
    aliases: []
    usage: createbow
  vbinfo:
    permission: viperbows.command.vbinfo
    permission-message: No.
    description: Info about the currently held ViperBow
    aliases: []
    usage: bowid
  vbsave: # Temporary command
    permission: viperbows.command.vbsave
    permission-message: No.
    description: Save all ViperBows to a file
    aliases: []
    usage: vbsave
  vbload: # Temporary command
    permission: viperbows.command.vbload
    permission-message: No.
    description: Load all ViperBows from a file
    aliases: []
    usage: vbload
  vbedit:
    permission: viperbows.command.vbedit
    permission-message: No.
    description: Edit the currently held ViperBow
    aliases: []
    usage: vbedit